/**
 * dwlf-mcp-server — the mechanical half of STANDARDS.md, as ESLint rules.
 *
 * GENERATED by `lgtm standards init` on 2026-09-10 — do not edit by hand.
 * Change a stance or threshold in STANDARDS.md and re-run init; both move together.
 *
 * Severity is "warn" on purpose: adopting thresholds on an existing codebase
 * lights up legacy that predates them. Standards are new-code scoped, so lint the
 * diff rather than the world in CI:
 *     npx eslint $(git diff --name-only origin/main... | grep -E "\.[jt]sx?$")
 *
 * Wire it into your existing flat config (path is relative to the repo root —
 * adjust if your ESLint config lives elsewhere, e.g. a monorepo package):
 *     import standardsRules from './.lgtm/standards.eslint.js';
 *     // then inside your config object:  rules: { ...standardsRules, ...yourOverrides }
 */

export const standardsRules = {
  // FUN-1 · Function size
  'max-lines-per-function': ['warn', { max: 130, skipBlankLines: true, skipComments: true }],
  // XP-16 · Complexity caps over length caps (cyclomatic)
  'complexity': ['warn', 20],
  // FMT-2 · Small files
  'max-lines': ['warn', { max: 1040, skipBlankLines: true, skipComments: true }],
  // FUN-2 · Shallow nesting
  'max-depth': ['warn', 3],
  // F1 · Few arguments
  'max-params': ['warn', 3],
  // G12 · No clutter
  'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
  // G9 · Dead code
  'no-unreachable': 'warn',
  // G29 · Positive conditionals
  'no-negated-condition': 'warn',
  // XP-17 · Only throw Error
  'no-throw-literal': 'warn',
};

/*
 * Worth adopting, but each needs a plugin this fragment cannot assume is installed.
 * Add the plugin, then add the rule:
 *   - sonarjs/cognitive-complexity at [warn, 15] — FUN-1 — the PRIMARY gate (nesting-aware; guard clauses free). Requires eslint-plugin-sonarjs.
 *   - @typescript-eslint/no-explicit-any at warn — XP-18 · No any; unknown at boundaries. Requires typescript-eslint (TS repos).
 *   - @typescript-eslint/ban-ts-comment at warn — G4 · No overridden safeties. Requires typescript-eslint (TS repos).
 *   - jest/no-disabled-tests at warn — T4 · A skipped test is a question, not a silencer. Requires eslint-plugin-jest.
 */

export default standardsRules;
